# Copyright (c) 2024 DSR Corporation, Denver, Colorado.
# https://www.dsr-corporation.com
# SPDX-License-Identifier: Apache-2.0

name: Create new release and publish NPM package

on:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # pulls all commits, needed for proper changelog generation
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup

      # anchor to the smallest npm version supporting trusted publishing
      - name: Update npm
        run: npm install -g npm@11.5.1

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run release
        run: yarn release --ci --no-increment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
